"""Adiciona tabela Assinaturas e relacoes dela com o usuario

Revision ID: 237ca0b4565c
Revises: 84d102c74c37
Create Date: 2025-08-08 04:13:16.341146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237ca0b4565c'
down_revision = '84d102c74c37'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maior_plano', sa.String(length=50), nullable=True))

    op.execute(
        "UPDATE \"user\" SET maior_plano = 'gratuito' WHERE maior_plano IS NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.String(length=50), nullable=False),
    sa.Column('data_assinatura', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_expiracao', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('maior_plano', existing_type=sa.String(length=50), nullable=False)
        batch_op.add_column(sa.Column('id_assinatura_ativa', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'assinaturas', ['id_assinatura_ativa'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_assinatura_ativa')
        batch_op.drop_column('maior_plano')

    op.drop_table('assinaturas')
    # ### end Alembic commands ###
