"""Reestrutura a tabela de eventos com novos campos

Revision ID: 243cb7a77c0b
Revises: e165b8861113
Create Date: 2025-09-10 01:23:32.210802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243cb7a77c0b'
down_revision = 'e165b8861113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_capa_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('descricao_breve', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('roteiro_publico', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('roteiro_privado', sa.Text(), nullable=True))
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('roteiro_privado')
        batch_op.drop_column('roteiro_publico')
        batch_op.drop_column('descricao_breve')
        batch_op.drop_column('imagem_capa_url')

    # ### end Alembic commands ###
