"""renoemado campos para imagem_banner_...

Revision ID: 3d11a4391b64
Revises: a06623122409
Create Date: 2025-09-14 17:26:00.809645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d11a4391b64'
down_revision = 'a06623122409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_banner_desktop_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('imagem_banner_mobile_url', sa.String(length=512), nullable=True))
        batch_op.drop_column('imagem_capa_desktop_url')
        batch_op.drop_column('imagem_capa_mobile_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_capa_mobile_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imagem_capa_desktop_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.drop_column('imagem_banner_mobile_url')
        batch_op.drop_column('imagem_banner_desktop_url')

    # ### end Alembic commands ###
