"""field(imagem_capa_mobile_url) adicionado

Revision ID: a06623122409
Revises: 243cb7a77c0b
Create Date: 2025-09-14 16:47:47.836006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06623122409'
down_revision = '243cb7a77c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_capa_desktop_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('imagem_capa_mobile_url', sa.String(length=512), nullable=True))
        batch_op.drop_column('imagem_capa_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_capa_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.drop_column('imagem_capa_mobile_url')
        batch_op.drop_column('imagem_capa_desktop_url')

    # ### end Alembic commands ###
