"""Add coluna meses_consecutivos em Assinatura

Revision ID: b0feace0744e
Revises: 237ca0b4565c
Create Date: 2025-08-11 19:52:06.032339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0feace0744e'
down_revision = '237ca0b4565c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assinaturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meses_consecutivos', sa.Integer(), nullable=True))

    op.execute(
        "UPDATE \"assinaturas\" SET meses_consecutivos = 1 WHERE meses_consecutivos IS NULL"
    )

    with op.batch_alter_table('assinaturas', schema=None) as batch_op:
        batch_op.alter_column('meses_consecutivos', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assinaturas', schema=None) as batch_op:
        batch_op.drop_column('meses_consecutivos')

    # ### end Alembic commands ###
