"""Adiciona coluna telefone a User

Revision ID: b4b8be0dbede
Revises: b0feace0744e
Create Date: 2025-08-12 21:25:49.761916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b8be0dbede'
down_revision = 'b0feace0744e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
