"""Adiciona a tabela de eventos

Revision ID: e165b8861113
Revises: b4b8be0dbede
Create Date: 2025-09-06 23:27:59.686095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e165b8861113'
down_revision = 'b4b8be0dbede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_evento', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=200), nullable=False),
    sa.Column('is_publico', sa.Boolean(), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_admin'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    # ### end Alembic commands ###
